- name: mysql configuration
  hosts: Mysql
  become: yes
  tasks:
  - name: install MySQL server
    ansible.builtin.package:
      name: mysql-server
      state: present

  - name: start myql server
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes
      
